# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

modules:
  - repo: https://github.com/beckn/beckn-onix
    version: v1.0.0
    name: github.com/beckn/beckn-onix
    plugins:
      schemavalidator: pkg/plugin/implementation/schemavalidator/cmd
      signvalidator: pkg/plugin/implementation/signvalidator/cmd
      router: pkg/plugin/implementation/router/cmd
      reqpreprocessor: pkg/plugin/implementation/reqpreprocessor/cmd
      signer: pkg/plugin/implementation/signer/cmd
    images:
      adapter:
        dockerfile: Dockerfile.adapter
        tag: latest
  - name: github.com/google/dpi-accelerator-beckn-onix
    path: .
    plugins:
      rediscache: plugins/rediscache/cmd
      pubsubpublisher: plugins/pubsubpublisher/cmd
      inmemorysecretkeymanager: plugins/inmemorysecretkeymanager/cmd
# registry: <REGISTRY_URL>
output: ./deploy/onix-installer/adapter_artifacts/plugins
zipFileName: plugins_bundle.zip
# gsPath: gs://<BucketName>/plugins/
goVersion: 1.24
